
import type { Metadata } from "next";
// import { Poppins } from "next/font/google";
import SideBar from "./component/Sidebar";
import { getSession } from "../actions/getUser";
// import tasksList from "@/models/tasks-list";
// import { TaskList } from "../data/Tasks";
// import prisma from "@/lib/prisma";


// const poppins = Poppins({
//   subsets: ["latin"],
//   variable: "--font-poppins",
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
// });


export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getSession();
      console.log(session?.user?.email);

      // const tasksLists = await tasksList.find({userEmail: {$in: [session?.user?.email]}})
      // const jTasklists = JSON.parse(JSON.stringify(tasksLists));

      // const tasksList = await prisma.taskList.findMany({
      //   where: {
      //     userEmail: session?.user?.email
      //   }
      // })

  return (
    
        <div className="flex lg:flex-row flex-col">
        <SideBar email={session?.user?.email} /* tasksList={tasksList} */ />
        {children}
        </div>
        
  );
}
